version: 2
jobs:
    test:
        docker:
            - image: circleci/node:10.16.2

        working_directory: ~/repo

        steps:
            - checkout

            # use existing cache for faster dep install
            - restore_cache:
                  name: Restore Yarn Package Cache
                  keys:
                      - yarn-packages-{{ checksum "yarn.lock" }}

            - run:
                  name: Install Dependencies
                  command: yarn install --frozen-lockfile

            - run: yarn test

            # save cache for future use
            - save_cache:
                  name: Save Yarn Package Cache
                  key: yarn-packages-{{ checksum "yarn.lock" }}
                  paths:
                      - ~/.cache/yarn

    build:
        docker:
            - image: circleci/node:10.16.2

        working_directory: ~/repo

        steps:
            - checkout

            # use existing cache for faster dep install
            - restore_cache:
                  name: Restore Yarn Package Cache
                  keys:
                      - yarn-packages-{{ checksum "yarn.lock" }}

            - run:
                  name: Install Dependencies
                  command: yarn install --frozen-lockfile

            - run:
                  name: Gatsby Build
                  command: ./node_modules/.bin/gatsby build

            # save cache for future use
            - save_cache:
                  name: Save Yarn Package Cache
                  key: yarn-packages-{{ checksum "yarn.lock" }}
                  paths:
                      - ~/.cache/yarn

    test-build-firebasedeploy:
        docker:
            - image: circleci/node:10.16.2

        working_directory: ~/repo

        steps:
            - checkout

            # use existing cache for faster dep install
            - restore_cache:
                  name: Restore Yarn Package Cache
                  keys:
                      - yarn-packages-{{ checksum "yarn.lock" }}

            - run:
                  name: Install Dependencies
                  command: yarn install --frozen-lockfile

            - run: yarn test

            - run:
                  name: Gatsby Build
                  command: ./node_modules/.bin/gatsby build

            - run:
                  name: Firebase Deploy
                  command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
    version: 2
    test-build-workflow:
        jobs:
            - test
            - build:
                  requires:
                      - test

    test-build-firebasedeploy-workflow:
        jobs:
            - test-build-firebasedeploy:
                  filters:
                      branches:
                          only:
                              - master
