name: Continuous Integration
on:
    push:
        branches:
            - master
    #         - '*' # matches every branch
    #         - '*/*' # matches every branch containing a '/'
    #     #    - '!master' # excludes master

jobs:
    continuous-integration:
        name: CI
        # lowply/deploy-firebase@v0.0.2 requires linux
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - run: yarn install
            - run: yarn run test
            - run: yarn run build
            - name: Deploy to Firebase
              uses: lowply/deploy-firebase@v0.0.2
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
                  FIREBASE_PROJECT: Portfolio
