name: Continuous Integration
on:
    push:
        branches:
            - '*' # matches every branch
            - '*/*' # matches every branch containing a '/'
            - '!master' # excludes master

jobs:
    continuous-integration:
        name: CI
        runs-on: windows-2019
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - run: yarn install
            - run: yarn run test
            - run: yarn run build
            - run: yarn run firebase:deploy #create a package.json script
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
