name: Continuous Integration
on:
    push:
        branches:
            - '*' # matches every branch
            - '*/*' # matches every branch containing a '/'
            - '!master' # excludes master

jobs:
    continuous-integration:
        name: CI
        runs-on: windows-2019
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - run: |
                  yarn install
                  yarn run test
                  yarn run build
