name: 'Continuous Integration'

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master

jobs:
    build_test:
        name: 'Build and test'
        strategy:
            matrix:
                node_version: [8, 10]
                os: [ubuntu-18.04, windows-2019]

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  version: ${{ matrix.node_version }}

            - name: 'installing yarn'
              run: npm install -g yarn

            - name: 'run build'
              run: yarn run build

            - name: 'run test'
              run: yarn run test
